export type Form = {
  inputName: string;
  inputPhone: string;
  inputCountry: string;
  inputEmail: string;
  inputMessage: string;
  buttonText: string;
  agreementText: string;
  agreementLinkLabel: string;
  agreementLinkDestination: string;
  validationNameRequired: string;
  validationNameTooShort: string;
  validationNameTooLong: string;
  validationPhoneRequired: string;
  validationPhoneTooShort: string;
  validationPhoneTooLong: string;
  validationPhoneInvalid: string;
  validationCountryRequired: string;
  validationEmailRequired: string;
  validationEmailInvalid: string;
  validationMessageRequired: string;
  validationAgreementRequired: string;
  validationAgreementOneOf: string;
  successMessage: string;
  errorMessage: string;
  spamBlockedMessage: string;
};
